import adminApi from "./adminApi";

/* =====================================================
   ADMIN ORDERS
===================================================== */

export const getAdminOrders = async () => {
  const response = await adminApi.get("/orders");
  return response.data;
};

export const getAdminOrder = async (id) => {
  const response = await adminApi.get(`/order/${id}`);
  return response.data;
};

export const updateOrderStatus = async (
  orderId,
  status,
  remark = ""
) => {
  const response = await adminApi.put(
    `/order/status/${orderId}`,
    {
      status,
      remark,
    }
  );

  return response.data;
};

/* =====================================================
   OUTBOUND COURIER ASSIGNMENT

   Backend:
   PUT /api/order/assign/:orderId

   Body:
   {
     courierId,
     estimatedDelivery
   }

   Tracking number is generated by backend.
===================================================== */

export const assignCourier = async (
  orderId,
  courierId,
  estimatedDelivery
) => {
  const response = await adminApi.put(
    `/order/assign/${orderId}`,
    {
      courierId,
      estimatedDelivery,
    }
  );

  return response.data;
};

/* =====================================================
   UPDATE TRACKING
===================================================== */

export const updateTracking = async (
  orderId,
  trackingNumber,
  trackingUrl = ""
) => {
  const response = await adminApi.put(
    `/order/tracking/${orderId}`,
    {
      trackingNumber,
      trackingUrl,
    }
  );

  return response.data;
};

/* =====================================================
   CHANGE COURIER
===================================================== */

export const changeCourier = async (
  orderId,
  courierId,
  trackingNumber,
  estimatedDelivery
) => {
  const response = await adminApi.put(
    `/courier/order/change/${orderId}`,
    {
      courierId,
      trackingNumber,
      estimatedDelivery,
    }
  );

  return response.data;
};

/* =====================================================
   COURIER DETAILS
===================================================== */

export const getCourierDetails = async (orderId) => {
  const response = await adminApi.get(
    `/courier/order/${orderId}`
  );

  return response.data;
};

/* =====================================================
   RETURNS
===================================================== */

export const requestReturn = async (orderId, payload = {}) => {
  const response = await adminApi.put(
    `/return/request/${orderId}`,
    payload
  );

  return response.data;
};

export const approveReturn = async (orderId, remark = "") => {
  const response = await adminApi.put(
    `/return/approve/${orderId}`,
    { remark }
  );

  return response.data;
};

export const rejectReturn = async (orderId, remark = "") => {
  const response = await adminApi.put(
    `/return/reject/${orderId}`,
    { remark }
  );

  return response.data;
};

export const assignReturnCourier = async (
  orderId,
  courierId,
  trackingNumber,
  estimatedDelivery
) => {
  const response = await adminApi.put(
    `/return/assign-courier/${orderId}`,
    {
      courierId,
      trackingNumber,
      estimatedDelivery,
    }
  );

  return response.data;
};

export const returnPickedUp = async (orderId, remark = "") => {
  const response = await adminApi.put(
    `/return/picked/${orderId}`,
    { remark }
  );

  return response.data;
};

export const receiveReturnedProduct = async (
  orderId,
  remark = ""
) => {
  const response = await adminApi.put(
    `/return/received/${orderId}`,
    { remark }
  );

  return response.data;
};

export const inspectReturnedProduct = async (
  orderId,
  inspectionStatus,
  remark = ""
) => {
  const response = await adminApi.put(
    `/return/inspection/${orderId}`,
    {
      inspectionStatus,
      remark,
    }
  );

  return response.data;
};

export const completeRefund = async (
  orderId,
  remark = ""
) => {
  const response = await adminApi.put(
    `/return/refund-complete/${orderId}`,
    { remark }
  );

  return response.data;
};

/* =====================================================
   DEFAULT EXPORT
===================================================== */

export default {
  getAdminOrders,
  getAdminOrder,
  updateOrderStatus,
  assignCourier,
  updateTracking,
  changeCourier,
  getCourierDetails,
  requestReturn,
  approveReturn,
  rejectReturn,
  assignReturnCourier,
  returnPickedUp,
  receiveReturnedProduct,
  inspectReturnedProduct,
  completeRefund,
};
